### ISSUE TITLE
Add support for any Thymeleaf 2.1 features that need to be reflected in content assist

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-extras-eclipse-plugin#27]
Anything being added for Thymeleaf 2.1 that affects content assist needs to be added to this plugin.  Can be derived from the Thymeleaf 2.1 milestone closed issues list: https://github.com/thymeleaf/thymeleaf/issues?milestone=1&page=1&state=closed

Currently, these changes are:
- [ ] `th:replace` as a synonym for `th:substituteby` (https://github.com/thymeleaf/thymeleaf/issues/69)
- [ ] `th:ref` (https://github.com/thymeleaf/thymeleaf/issues/196)
- [ ] `th:inject` (https://github.com/thymeleaf/thymeleaf/issues/68)
- [ ] `th:block` (https://github.com/thymeleaf/thymeleaf/issues/182)
- [ ] Parser-level comment blocks (https://github.com/thymeleaf/thymeleaf/issues/183)
- [ ] Prototype-only comment blocks (https://github.com/thymeleaf/thymeleaf/issues/185)
- [ ] `th:assert` (https://github.com/thymeleaf/thymeleaf/issues/178)
- [ ] Fragment signatures (https://github.com/thymeleaf/thymeleaf/issues/181, not sure how to implement this one, might need some kind of fragment scanner, but that feature is still on the TODO list)
- [ ] HTML5 data-\* attributes (https://github.com/thymeleaf/thymeleaf/issues/93)

See also here to make sure I get everything: http://www.thymeleaf.org/whatsnew21.html

**Comment by ultraq** [comment]
Have created individual issues for all the new 2.1 features, based on the [What's New in Thymeleaf 2.1](http://www.thymeleaf.org/whatsnew21.html) page after the 2.1.0-beta2 release.  Will be easier to work with those smaller issues, and it'll feel like progress is actually being made once I start tackling lots of little issues instead of this massive one.
